[package]
name = "loong-kernel"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
loac.workspace = true
loong-contracts.workspace = true
uuid.workspace = true
async-trait.workspace = true
tokio = { workspace = true, features = ["macros", "rt", "fs", "net", "time"] }
thiserror.workspace = true
serde_json.workspace = true

[lints]
workspace = true

[features]
default = ["fs"]
fs = []
