[package]
name = "loong-kernel"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
actix = "0.13.5"
loong-access.workspace = true
loong-contracts.workspace = true
loong-core.workspace = true
uuid.workspace = true
async-trait.workspace = true
tokio = { workspace = true, features = ["macros", "rt", "fs", "net", "time"] }

[lints]
workspace = true
