[package]
name = "loac-macros"
version = "0.1.1"
edition.workspace = true
rust-version = "1.97.1"
license.workspace = true
description = "Procedural macros for loac"
repository = "https://github.com/eastreams/loong"

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "3.5.0"
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = { version = "3.0.3", features = ["full"] }

[dev-dependencies]
actor-api = { package = "loac", path = "../actor", version = "0.1.0" }
trybuild = "1.0.118"

[lints]
workspace = true
