[package]
name = "loong-tools"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Internal support crate for Loong: concrete builtin tool implementations"
repository.workspace = true
homepage.workspace = true

[lib]
name = "loong_tools"

[features]
default = []
file = []

[dependencies]
async-trait.workspace = true
loong-contracts.workspace = true
loong-core.workspace = true
loong-kernel.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[lints]
workspace = true
