[package]
name = "loong-tools"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Internal support crate for Loong: concrete builtin tool implementations"
repository.workspace = true
homepage.workspace = true

[lib]
name = "loong_tools"

[features]
default = []
file = []

[dependencies]
async-trait.workspace = true
loong-contracts = { package = "loong-contracts", version = "0.1.2-alpha.1", path = "../contracts" }
loong-core = { package = "loong-core", version = "0.1.2-alpha.1", path = "../loong-core" }
loong-kernel = { package = "loong-kernel", version = "0.1.2-alpha.1", path = "../kernel" }
serde_json.workspace = true

[lints]
workspace = true
