mod interleaving;
mod messaging;
mod supervision;

pub use interleaving::{DynamicInterleaving, Interleaving, NoInterleaving, UnboundedInterleaving};
pub use messaging::{DynamicMailbox, Mailbox, NoMessaging, UnboundedMailbox};
pub use supervision::{Children, DynamicChildren, NoChildren, UnboundedChildren};

mod sealed {
    pub trait Messaging {}
    pub trait Supervision {}
    pub trait Interleaving {}
}

/// Configuration generated by an actor attribute.
///
/// Use `#[actor]` on an `Actor` implementation.
/// Direct implementations are unsupported.
pub trait ActorConfig {
    /// Selects public messaging and reply scheduling.
    #[doc(hidden)]
    type Messaging: MessagingConfig;

    /// Selects direct-child ownership.
    #[doc(hidden)]
    type Supervision: SupervisionConfig;
}

/// A sealed messaging configuration.
#[doc(hidden)]
pub trait MessagingConfig: sealed::Messaging {}

/// A sealed supervision configuration.
#[doc(hidden)]
pub trait SupervisionConfig: sealed::Supervision {}

/// A sealed interleaving configuration.
#[doc(hidden)]
pub trait InterleavingConfig: sealed::Interleaving {}
