[package]
name = "loong-cli"
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "loong"
path = "src/main.rs"

[dependencies]
agent.workspace = true
context.workspace = true
contracts.workspace = true
loac.workspace = true
provider.workspace = true
provider-openai.workspace = true
tokio = { workspace = true, features = ["io-std", "macros", "rt-multi-thread", "sync"] }

[lints]
workspace = true
