[package]
name = "loong-context"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
loong-contracts.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
uuid.workspace = true

[lints]
workspace = true
